"use client";
import {useEffect,useState} from 'react';
const checks=['identity_status','phone_status','address_status','licence_status','guarantor_status','reference_status','interview_status','field_verification_status'];
const labels:any={identity_status:'Identité',phone_status:'Téléphone',address_status:'Résidence',licence_status:'Permis/licence',guarantor_status:'Garant',reference_status:'Référence',interview_status:'Entretien',field_verification_status:'Vérification terrain',ID_CARD:'Pièce d’identité',DRIVER_LICENSE:'Permis/licence',RESIDENCE_PROOF:'Résidence',GUARANTOR_ID:'ID du garant'};
export default function Admin(){
 const [auth,setAuth]=useState(false),[email,setEmail]=useState(''),[pw,setPw]=useState(''),[rows,setRows]=useState<any[]>([]),[sel,setSel]=useState<any>(null),[docs,setDocs]=useState<any[]>([]),[error,setError]=useState(''),[me,setMe]=useState<any>(null);
 async function load(){const r=await fetch('/api/admin/candidates',{cache:'no-store'});if(r.ok){setRows((await r.json()).data);setAuth(true)}else setAuth(false)}
 async function check(){const r=await fetch('/api/admin/me',{cache:'no-store'});if(r.ok){const d=await r.json();setMe(d.user);setAuth(true);load()}else setAuth(false)}
 useEffect(()=>{check()},[]);
 async function login(){setError('');const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,pw})});if(r.ok){await check()}else{const d=await r.json().catch(()=>({}));setError(d.error||'Connexion impossible.')}}
 async function loadDocs(id:string){const x=await fetch('/api/admin/candidates/'+id+'/documents'); if(x.ok)setDocs((await x.json()).data||[])}
 async function update(id:string,patch:any){const r=await fetch('/api/admin/candidates/'+id+'/status',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});const d=await r.json();if(!r.ok){setError(d.error);return} setSel(d.data);load()}
 if(!auth)return <main className="login"><div className="form"><h1>DBM Candidate Pilot</h1><p className="muted">Administration sécurisée — Supabase Auth</p><input type="email" autoComplete="username" placeholder="Admin email" value={email} onChange={e=>setEmail(e.target.value)} style={{width:'100%',padding:12,margin:'10px 0'}}/><input type="password" autoComplete="current-password" placeholder="Mot de passe" value={pw} onChange={e=>setPw(e.target.value)} onKeyDown={e=>e.key==='Enter'&&login()} style={{width:'100%',padding:12,margin:'10px 0'}}/><button className="btn primary" onClick={login}>Connexion</button>{error&&<p className="error">{error}</p>}<p className="hint">Les comptes administrateurs sont créés dans le projet Supabase pilote et autorisés dans la table admin_users.</p></div></main>;
 return <main className="dashboard"><div className="wrap"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h1>Contrôle & sélection des candidats</h1><p className="muted">Connecté : {me?.email||''}. Aucun candidat ne peut être APPROVED tant que les 8 contrôles obligatoires et les pièces requises ne sont pas vérifiés.</p></div><button className="btn outline" onClick={async()=>{await fetch('/api/admin/logout',{method:'POST'});location.reload()}}>Déconnexion</button></div>{error&&<p className="error">{error}</p>}<div className="table-wrap"><table className="table"><thead><tr><th>Réf.</th><th>Candidat</th><th>Score</th><th>Pré-sélection</th><th>Décision</th><th>Contrôles</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.applicant_id}</b></td><td>{r.name}<br/><small>{r.phone}</small></td><td>{r.preliminary_score}/100</td><td>{r.pre_screening_status}</td><td>{r.final_decision}</td><td>{checks.filter(k=>r[k]==='VERIFIED').length}/8</td><td><button className="btn outline" onClick={()=>{setSel(r);loadDocs(r.id)}}>Ouvrir</button></td></tr>)}</tbody></table></div>{sel&&<div className="form" style={{marginTop:20}}><h2>{sel.name} — {sel.applicant_id}</h2><p className="muted">Score préliminaire : {sel.preliminary_score}/100. La confiance repose sur des vérifications documentées.</p><div className="plans" style={{gridTemplateColumns:'repeat(2,1fr)'}}>{checks.map(k=><div className="plan" key={k}><b>{labels[k]}</b><select value={sel[k]} onChange={e=>setSel({...sel,[k]:e.target.value})}><option>PENDING</option><option>VERIFIED</option><option>FAILED</option></select><button className="btn primary" style={{marginTop:8}} onClick={()=>update(sel.id,{[k]:sel[k]})}>Enregistrer</button></div>)}</div><div className="actions"><button className="btn outline" onClick={()=>update(sel.id,{final_decision:'REJECTED'})}>Refuser</button><button className="btn primary" onClick={()=>update(sel.id,{final_decision:'APPROVED'})}>Approuver</button></div><h3>Pièces justificatives</h3>{docs.length===0?<p className="hint">Aucune pièce reçue.</p>:docs.map(d=><div className="plan" key={d.id}><b>{labels[d.document_type]||d.document_type}</b> — {d.status} {d.signed_url&&<a href={d.signed_url} target="_blank">Ouvrir</a>}<select value={d.status} onChange={e=>setDocs(docs.map(x=>x.id===d.id?{...x,status:e.target.value}:x))}><option>PENDING</option><option>VERIFIED</option><option>FAILED</option></select><button className="btn primary" onClick={async()=>{const x=await fetch('/api/admin/candidates/'+sel.id+'/documents',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({documentId:d.id,status:d.status})});if(x.ok)loadDocs(sel.id)}}>Enregistrer</button></div>)}<p className="hint">L’approbation est techniquement bloquée si un contrôle obligatoire ou une pièce requise n’est pas VERIFIED.</p></div>}</div></main>
}
