import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import crypto from 'crypto';
import { calculatePreliminaryScore } from '@/lib/scoring';
import { getSupabaseAdmin } from '@/lib/supabase-admin';

const schema=z.object({name:z.string().trim().min(2).max(120),phone:z.string().trim().min(8).max(30),dob:z.string().min(8).max(20),address:z.string().trim().min(5).max(250),source:z.string().max(30).default('Direct'),campaign:z.string().max(120).optional(),utmMedium:z.string().max(120).optional(),experienceMonths:z.number().int().min(0).max(60),licence:z.enum(['yes','no','pending']),activity:z.string().max(80),activityDuration:z.string().max(50),residenceDuration:z.string().max(10),professional:z.enum(['yes','no']),dailyRevenue:z.number().min(0).max(1000000),dailyFuel:z.number().min(0).max(1000000),dailyObligations:z.number().min(0).max(1000000),dailyOtherCost:z.number().min(0).max(1000000),plan:z.enum(['fast','balance','flex']),consent:z.boolean().refine(v=>v===true)});
const id=()=>`DBM-CUS-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;
const recent=new Map<string,number>();
function limited(ip:string){const now=Date.now(); const prev=recent.get(ip)||0; if(now-prev<30000)return true; recent.set(ip,now); if(recent.size>5000) for(const [k,v] of recent) if(now-v>300000) recent.delete(k); return false;}
const token=()=>crypto.randomBytes(24).toString('base64url');
export async function POST(req:NextRequest){try{const ip=(req.headers.get('x-forwarded-for')||'unknown').split(',')[0].trim(); if(limited(ip)) return NextResponse.json({error:'Trop de tentatives. Veuillez patienter 30 secondes.'},{status:429});const data=schema.parse(await req.json()); const calc=calculatePreliminaryScore({...data,name:data.name,phone:data.phone,address:data.address}); const sb=getSupabaseAdmin(); for(let i=0;i<5;i++){const applicantId=id(), verificationToken=token(); const {data:row,error}=await sb.from('candidate_applications').insert({applicant_id:applicantId,verification_token:verificationToken,name:data.name,phone:data.phone,dob:data.dob,address:data.address,source:data.source,campaign:data.campaign||null,utm_medium:data.utmMedium||null,experience_months:data.experienceMonths,licence:data.licence,activity:data.activity,activity_duration:data.activityDuration,residence_duration:data.residenceDuration,professional:data.professional,daily_revenue:data.dailyRevenue,daily_fuel:data.dailyFuel,daily_obligations:data.dailyObligations,daily_other_cost:data.dailyOtherCost,selected_plan:data.plan,target_amount:calc.target,target_daily:calc.daily,net_daily_capacity:calc.capacity,capacity_ratio:calc.ratio,preliminary_score:calc.score,pre_screening_status:calc.status,consent_at:new Date().toISOString()}).select('id').single(); if(!error){await sb.from('candidate_audit_log').insert({candidate_id:row.id,actor:'SYSTEM',action:'APPLICATION_CREATED',details:{score:calc.score,status:calc.status}}); return NextResponse.json({applicantId,name:data.name,status:calc.status,score:calc.score,verificationToken});}} throw new Error('Unable to create unique candidate reference.');}catch(e:any){return NextResponse.json({error:e?.issues?.[0]?.message||e?.message||'Invalid application.'},{status:400})}}
