'use client';
import { FormEvent, useEffect, useState } from 'react';
import { PLANS } from '@/lib/scoring';

const sources = ['Direct','Facebook','Instagram','TikTok','WhatsApp'];
const experienceOptions = [{v:0,l:'Moins de 3 mois'},{v:3,l:'3–5 mois'},{v:6,l:'6–11 mois'},{v:12,l:'1 an ou plus'}];

export default function Home() {
  const [plan,setPlan]=useState('balance'); const [step,setStep]=useState(1); const [result,setResult]=useState<any>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const [form,setForm]=useState<any>({name:'',phone:'',dob:'',address:'',source:'Direct',experienceMonths:6,licence:'yes',activity:'Moto-taxi',activityDuration:'6–12 mois',residenceDuration:'1',professional:'yes',dailyRevenue:'',dailyFuel:'',dailyObligations:'',dailyOtherCost:'0',consent:false});
  const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));
  const params=typeof window!=='undefined'?new URLSearchParams(window.location.search):null;
  const sourceMap:any={fb:'Facebook',facebook:'Facebook',ig:'Instagram',instagram:'Instagram',tt:'TikTok',tiktok:'TikTok',wa:'WhatsApp',whatsapp:'WhatsApp'};
  const tracked=params?sourceMap[(params.get('utm_source')||'').toLowerCase()]:null;
  useEffect(()=>{ if(tracked) set('source',tracked); }, [tracked]);
  function valid1(){return form.name.trim()&&form.phone.trim()&&form.dob&&form.address.trim()}
  async function submit(e:FormEvent){e.preventDefault();setError(''); if(!form.consent){setError('Veuillez accepter le traitement des données avant de soumettre.');return} setLoading(true); try{const r=await fetch('/api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,plan,experienceMonths:Number(form.experienceMonths),dailyRevenue:Number(form.dailyRevenue),dailyFuel:Number(form.dailyFuel),dailyObligations:Number(form.dailyObligations),dailyOtherCost:Number(form.dailyOtherCost),campaign:params?.get('utm_campaign')||'',utmMedium:params?.get('utm_medium')||''})}); const data=await r.json(); if(!r.ok) throw new Error(data.error||'Impossible d’enregistrer la candidature.'); setResult(data); }catch(err:any){setError(err.message)}finally{setLoading(false)}}
  if(result) { const verifyUrl=typeof window!=='undefined'?`${window.location.origin}/verify/${result.verificationToken}`:''; const wa=process.env.NEXT_PUBLIC_WHATSAPP_NUMBER||''; const waHref=wa?`https://wa.me/${wa.replace(/\D/g,'')}?text=${encodeURIComponent(`Bonjour D-Boss-Motos, je viens de déposer ma candidature ${result.applicantId}. Je souhaite poursuivre la vérification.`)}`:''; return <main><div className="top"><div className="wrap"><span>🏍️ D-BOSS MOTOS • PILOTE CANDIDATS</span><span>FR / EN</span></div></div><section><div className="wrap" style={{maxWidth:720}}><div className="success"><h1>✅ Candidature reçue</h1><p>Merci {result.name}. Votre référence est :</p><h2>{result.applicantId}</h2><p>{result.status==='PRE_QUALIFIED'?'Votre profil répond aux conditions préliminaires. Vous pouvez maintenant poursuivre immédiatement avec la vérification du dossier.':'Votre dossier est enregistré pour étude et/ou vérifications complémentaires. La présélection ne constitue pas une approbation définitive.'}</p><div className="actions" style={{marginTop:20}}><a className="btn primary" href={verifyUrl}>📄 Continuer la vérification & téléverser les pièces</a>{waHref&&<a className="btn outline" href={waHref} target="_blank" rel="noreferrer">WhatsApp</a>}</div><p className="hint" style={{marginTop:16}}>Conservez votre référence et votre lien de vérification. Ne partagez pas ce lien privé avec une autre personne.</p></div></div></section></main>; }
  return <main><div className="top"><div className="wrap"><span>🏍️ D-BOSS MOTOS • Candidature en ligne</span><span>PILOTE INDÉPENDANT</span></div></div><header className="hero"><div className="wrap"><div className="nav"><div className="logo">D-BOSS <span>MOTOS</span></div><div>Candidatez en ligne</div></div><div className="hero-grid"><div><div className="eyebrow">Travaillez • Payez • Devenez propriétaire</div><h1>Votre moto.<br/>Votre activité.<br/><span style={{color:'#f1cf72'}}>Votre propriété.</span></h1><p>Soumettez votre candidature en ligne. Les candidats qui remplissent les conditions préliminaires sont contactés pour la suite.</p><a className="btn primary" href="#apply">🚀 CANDIDATER MAINTENANT</a></div><div className="hero-card"><h3>Présélection en 3 étapes</h3><div className="mini"><div className="icon">1</div><div><b>Candidature</b><small>Informations de départ.</small></div></div><div className="mini"><div className="icon">2</div><div><b>Présélection</b><small>Analyse préliminaire.</small></div></div><div className="mini"><div className="icon">3</div><div><b>Contact</b><small>Uniquement si les conditions sont remplies.</small></div></div></div></div></div></header>
  <section id="plans"><div className="wrap"><div className="title"><h2>Choisissez votre cadence</h2><p className="muted">Les durées publicitaires sont simples. Le calcul contractuel repose sur les jours réels de paiement, à raison de 6 jours par semaine.</p></div><div className="plans">{Object.entries(PLANS).map(([k,p],i)=><div className={'plan '+(k==='balance'?'featured':'')} key={k}><h3>{i===0?'🚀':i===1?'⚡':'🏆'} {p.label}</h3><div>À partir de {i===0?'4':i===1?'6':'8'} mois</div><div className="price">{p.target.toLocaleString('fr-FR')} F</div><div className="day">≈ {p.daily.toLocaleString('fr-FR')} F / jour</div><ul><li>6 jours de paiement / semaine</li><li>Présélection en ligne</li><li>Validation définitive après vérifications</li></ul><button className="btn primary" style={{width:'100%'}} onClick={()=>{setPlan(k);document.getElementById('apply')?.scrollIntoView({behavior:'smooth'})}}>Choisir</button></div>)}</div></div></section>
  <section id="apply" style={{background:'#eef2f6'}}><div className="wrap"><div className="title"><h2>Candidature pilote</h2><p className="muted">Ce portail est un environnement de test séparé du système de gestion opérationnel D-Boss-Motos.</p></div><div className="form-wrap"><div className="info"><h2>Avant de commencer</h2><ul><li>Préparez vos informations personnelles.</li><li>Indiquez des revenus et charges réalistes.</li><li>La présélection n'est pas une acceptation.</li><li>Un conseiller peut demander des preuves complémentaires.</li></ul></div><div className="form"><div style={{height:8,background:'#e8edf3',borderRadius:20,marginBottom:20}}><div style={{height:'100%',width:`${step/3*100}%`,background:'#d6a63a',borderRadius:20}}/></div><form onSubmit={submit}>{step===1&&<><h3>1. Identité & contact</h3><div className="row"><div className="field"><label>Nom complet *</label><input required value={form.name} onChange={e=>set('name',e.target.value)}/></div><div className="field"><label>Téléphone / WhatsApp *</label><input required inputMode="tel" value={form.phone} onChange={e=>set('phone',e.target.value)}/></div></div><div className="row"><div className="field"><label>Date de naissance *</label><input required type="date" value={form.dob} onChange={e=>set('dob',e.target.value)}/></div><div className="field"><label>Lieu / adresse de résidence *</label><input required value={form.address} onChange={e=>set('address',e.target.value)}/></div></div><div className="field"><label>Source</label><select value={form.source} onChange={e=>set('source',e.target.value)}>{sources.map(x=><option key={x}>{x}</option>)}</select></div><div className="actions"><span/><button type="button" className="btn primary" disabled={!valid1()} onClick={()=>setStep(2)}>Continuer →</button></div></>}
{step===2&&<><h3>2. Expérience & stabilité</h3><div className="row"><div className="field"><label>Expérience de conduite</label><select value={form.experienceMonths} onChange={e=>set('experienceMonths',e.target.value)}>{experienceOptions.map(x=><option key={x.v} value={x.v}>{x.l}</option>)}</select></div><div className="field"><label>Permis / licence</label><select value={form.licence} onChange={e=>set('licence',e.target.value)}><option value="yes">Oui</option><option value="no">Non</option><option value="pending">En cours</option></select></div></div><div className="row"><div className="field"><label>Activité principale</label><select value={form.activity} onChange={e=>set('activity',e.target.value)}>{['Moto-taxi','Livraison','Transport','Commerce','Salarié','Indépendant','Autre'].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Durée de l'activité</label><select value={form.activityDuration} onChange={e=>set('activityDuration',e.target.value)}>{['Moins de 6 mois','6–12 mois','1–2 ans','Plus de 2 ans'].map(x=><option key={x}>{x}</option>)}</select></div></div><div className="row"><div className="field"><label>Durée de résidence</label><select value={form.residenceDuration} onChange={e=>set('residenceDuration',e.target.value)}><option value="0">Moins de 6 mois</option><option value="1">6–12 mois</option><option value="2">Plus d'un an</option></select></div><div className="field"><label>Conduite professionnelle ?</label><select value={form.professional} onChange={e=>set('professional',e.target.value)}><option value="yes">Oui</option><option value="no">Non</option></select></div></div><div className="actions"><button type="button" className="btn outline" onClick={()=>setStep(1)}>← Retour</button><button type="button" className="btn primary" onClick={()=>setStep(3)}>Continuer →</button></div></>}
{step===3&&<><h3>3. Capacité & formule</h3><div className="row"><div className="field"><label>Revenu journalier moyen *</label><input required type="number" min="0" value={form.dailyRevenue} onChange={e=>set('dailyRevenue',e.target.value)}/></div><div className="field"><label>Carburant / coûts d'activité</label><input type="number" min="0" value={form.dailyFuel} onChange={e=>set('dailyFuel',e.target.value)}/></div></div><div className="row"><div className="field"><label>Charges essentielles</label><input type="number" min="0" value={form.dailyObligations} onChange={e=>set('dailyObligations',e.target.value)}/></div><div className="field"><label>Autres coûts</label><input type="number" min="0" value={form.dailyOtherCost} onChange={e=>set('dailyOtherCost',e.target.value)}/></div></div><div className="field"><label>Formule souhaitée</label><select value={plan} onChange={e=>setPlan(e.target.value)}>{Object.entries(PLANS).map(([k,p])=><option key={k} value={k}>{p.label} — {p.target.toLocaleString('fr-FR')} F — ≈ {p.daily.toLocaleString('fr-FR')} F/j</option>)}</select></div><div className="field"><label style={{display:'flex',gap:8,fontWeight:500}}><input type="checkbox" checked={form.consent} onChange={e=>set('consent',e.target.checked)}/> J'accepte l'utilisation de ces informations pour traiter ma candidature et effectuer les vérifications nécessaires.</label></div>{error&&<div className="error">{error}</div>}<div className="actions"><button type="button" className="btn outline" onClick={()=>setStep(2)}>← Retour</button><button className="btn primary" disabled={loading}>{loading?'Enregistrement…':'🚀 Soumettre ma candidature'}</button></div></>}
</form></div></div></div></section><footer style={{background:'#071b33',color:'#dce7f4',padding:'30px 0'}}><div className="wrap"><b>D-BOSS MOTOS — CANDIDATE PILOT</b><p>Portail de présélection indépendant. Les données de ce pilote ne sont pas reliées au système opérationnel D-Boss-Motos.</p></div></footer></main>;
}
